
language: haskell

notifications:
  email: false

dist: "trusty"

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

ghc:
  - "8.4"

python:
  - "3.6"

install:
  - cabal install --only-dependencies
  - pip3 install termcolor

script:
  - make
  - make test
